name: Lint
on: [push, pull_request]
jobs:
  lint-cxx:
    name: C++ Source Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check on C/C++ sources
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '15'
        exclude-regex: 'include/uring'
